//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""7eeb27d8-a95a-401c-8ff8-02fd0da35744"",
            ""actions"": [
                {
                    ""name"": ""Walking"",
                    ""type"": ""Value"",
                    ""id"": ""3034438d-ec3a-43ee-a9bd-d4a87fe3db56"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""6124d5cd-4de4-4259-afaa-6fa15e347e98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""e81bc8cc-23e5-4de7-adb0-2a2df610e448"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenStats"",
                    ""type"": ""Button"",
                    ""id"": ""81d3e22d-4b3d-4007-82b9-84e57231c5dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenPauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6671e1fe-907f-4f3c-a85a-7bbe4ba45ff6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Getup"",
                    ""type"": ""Button"",
                    ""id"": ""5beebd54-79b7-46b2-b9dc-1edc55bf2915"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3596fdbf-110e-4d43-9f27-b1ce40b566cb"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02f1f61e-a7b0-4a32-9a1a-1ef6d59a61d4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WSAD"",
                    ""id"": ""d2c463c1-c6c3-4fdf-965a-790deb40db1f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a41a6fbf-7248-49e3-939f-a0155ea7f69a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""73281f14-6768-44f9-a636-0767a253c747"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""09caf7c9-cf97-4764-a291-46d7089a8752"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1b636d04-a62b-4b3b-8f9e-0d469af5a80c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ef89ce51-979b-4206-82de-8706a23d8239"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ede5a4dc-30a8-4efa-894b-ccaac8377e54"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fc6b6374-d707-4f80-87d8-74a5da3dc832"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""45181ea9-5c5e-4c9d-9060-1adc9edec51b"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b7658759-fb8d-4fcd-af5c-4a33f1e50373"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f7e34dc0-c759-4be8-a12e-cd1dfa3cc307"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23c53e1b-171d-4818-a4df-fef516f84a97"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e57009a-8e23-41a6-958d-eaa2b19a496f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bcc40e0-6067-4ba0-8f64-f5a176088a0b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa864397-4613-4dd7-8775-797b9b67ca42"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenPauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ad21805-1361-47b8-ae69-ed1433b74a14"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenPauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb1289a4-d701-4567-847c-19cda3b453b5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Getup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9eea4ac-36cb-4239-82d5-a9ca2de4973c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Getup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InPauseMenu"",
            ""id"": ""8c3939ac-5ffa-447a-8812-da96331f9c4b"",
            ""actions"": [
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""47f6cfd7-284e-4e97-96c2-45fa21664c1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseStats"",
                    ""type"": ""Button"",
                    ""id"": ""73e78c72-12ec-4b53-abe3-c0879286dfed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""948e7817-75ba-4e2c-a3a3-7318cd1ad32d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1da38f44-447e-446a-b64d-a72b0740fda1"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aa8f5c5-0a3f-46f5-aa82-fb268499f868"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5ef5d27-34bc-4f3d-a8ec-52d4fe74e73c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InGameOver"",
            ""id"": ""dbaa651e-7792-4b9f-9ad5-6ca817bf1fc9"",
            ""actions"": [
                {
                    ""name"": ""GoToMM"",
                    ""type"": ""Button"",
                    ""id"": ""42745a7e-3df7-4297-9736-c87dd4698605"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e0aa966a-21d1-4066-b3fc-9099f343fec4"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoToMM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62116878-c5c5-4235-a465-f8be1edb1afc"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoToMM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Walking = m_OnFoot.FindAction("Walking", throwIfNotFound: true);
        m_OnFoot_Interact = m_OnFoot.FindAction("Interact", throwIfNotFound: true);
        m_OnFoot_Look = m_OnFoot.FindAction("Look", throwIfNotFound: true);
        m_OnFoot_OpenStats = m_OnFoot.FindAction("OpenStats", throwIfNotFound: true);
        m_OnFoot_OpenPauseMenu = m_OnFoot.FindAction("OpenPauseMenu", throwIfNotFound: true);
        m_OnFoot_Getup = m_OnFoot.FindAction("Getup", throwIfNotFound: true);
        // InPauseMenu
        m_InPauseMenu = asset.FindActionMap("InPauseMenu", throwIfNotFound: true);
        m_InPauseMenu_Return = m_InPauseMenu.FindAction("Return", throwIfNotFound: true);
        m_InPauseMenu_CloseStats = m_InPauseMenu.FindAction("CloseStats", throwIfNotFound: true);
        // InGameOver
        m_InGameOver = asset.FindActionMap("InGameOver", throwIfNotFound: true);
        m_InGameOver_GoToMM = m_InGameOver.FindAction("GoToMM", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_OnFoot_Walking;
    private readonly InputAction m_OnFoot_Interact;
    private readonly InputAction m_OnFoot_Look;
    private readonly InputAction m_OnFoot_OpenStats;
    private readonly InputAction m_OnFoot_OpenPauseMenu;
    private readonly InputAction m_OnFoot_Getup;
    public struct OnFootActions
    {
        private @PlayerInput m_Wrapper;
        public OnFootActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walking => m_Wrapper.m_OnFoot_Walking;
        public InputAction @Interact => m_Wrapper.m_OnFoot_Interact;
        public InputAction @Look => m_Wrapper.m_OnFoot_Look;
        public InputAction @OpenStats => m_Wrapper.m_OnFoot_OpenStats;
        public InputAction @OpenPauseMenu => m_Wrapper.m_OnFoot_OpenPauseMenu;
        public InputAction @Getup => m_Wrapper.m_OnFoot_Getup;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @Walking.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnWalking;
                @Walking.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnWalking;
                @Walking.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnWalking;
                @Interact.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Look.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @OpenStats.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOpenStats;
                @OpenStats.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOpenStats;
                @OpenStats.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOpenStats;
                @OpenPauseMenu.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOpenPauseMenu;
                @OpenPauseMenu.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOpenPauseMenu;
                @OpenPauseMenu.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnOpenPauseMenu;
                @Getup.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnGetup;
                @Getup.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnGetup;
                @Getup.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnGetup;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walking.started += instance.OnWalking;
                @Walking.performed += instance.OnWalking;
                @Walking.canceled += instance.OnWalking;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @OpenStats.started += instance.OnOpenStats;
                @OpenStats.performed += instance.OnOpenStats;
                @OpenStats.canceled += instance.OnOpenStats;
                @OpenPauseMenu.started += instance.OnOpenPauseMenu;
                @OpenPauseMenu.performed += instance.OnOpenPauseMenu;
                @OpenPauseMenu.canceled += instance.OnOpenPauseMenu;
                @Getup.started += instance.OnGetup;
                @Getup.performed += instance.OnGetup;
                @Getup.canceled += instance.OnGetup;
            }
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);

    // InPauseMenu
    private readonly InputActionMap m_InPauseMenu;
    private IInPauseMenuActions m_InPauseMenuActionsCallbackInterface;
    private readonly InputAction m_InPauseMenu_Return;
    private readonly InputAction m_InPauseMenu_CloseStats;
    public struct InPauseMenuActions
    {
        private @PlayerInput m_Wrapper;
        public InPauseMenuActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Return => m_Wrapper.m_InPauseMenu_Return;
        public InputAction @CloseStats => m_Wrapper.m_InPauseMenu_CloseStats;
        public InputActionMap Get() { return m_Wrapper.m_InPauseMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InPauseMenuActions set) { return set.Get(); }
        public void SetCallbacks(IInPauseMenuActions instance)
        {
            if (m_Wrapper.m_InPauseMenuActionsCallbackInterface != null)
            {
                @Return.started -= m_Wrapper.m_InPauseMenuActionsCallbackInterface.OnReturn;
                @Return.performed -= m_Wrapper.m_InPauseMenuActionsCallbackInterface.OnReturn;
                @Return.canceled -= m_Wrapper.m_InPauseMenuActionsCallbackInterface.OnReturn;
                @CloseStats.started -= m_Wrapper.m_InPauseMenuActionsCallbackInterface.OnCloseStats;
                @CloseStats.performed -= m_Wrapper.m_InPauseMenuActionsCallbackInterface.OnCloseStats;
                @CloseStats.canceled -= m_Wrapper.m_InPauseMenuActionsCallbackInterface.OnCloseStats;
            }
            m_Wrapper.m_InPauseMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Return.started += instance.OnReturn;
                @Return.performed += instance.OnReturn;
                @Return.canceled += instance.OnReturn;
                @CloseStats.started += instance.OnCloseStats;
                @CloseStats.performed += instance.OnCloseStats;
                @CloseStats.canceled += instance.OnCloseStats;
            }
        }
    }
    public InPauseMenuActions @InPauseMenu => new InPauseMenuActions(this);

    // InGameOver
    private readonly InputActionMap m_InGameOver;
    private IInGameOverActions m_InGameOverActionsCallbackInterface;
    private readonly InputAction m_InGameOver_GoToMM;
    public struct InGameOverActions
    {
        private @PlayerInput m_Wrapper;
        public InGameOverActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @GoToMM => m_Wrapper.m_InGameOver_GoToMM;
        public InputActionMap Get() { return m_Wrapper.m_InGameOver; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameOverActions set) { return set.Get(); }
        public void SetCallbacks(IInGameOverActions instance)
        {
            if (m_Wrapper.m_InGameOverActionsCallbackInterface != null)
            {
                @GoToMM.started -= m_Wrapper.m_InGameOverActionsCallbackInterface.OnGoToMM;
                @GoToMM.performed -= m_Wrapper.m_InGameOverActionsCallbackInterface.OnGoToMM;
                @GoToMM.canceled -= m_Wrapper.m_InGameOverActionsCallbackInterface.OnGoToMM;
            }
            m_Wrapper.m_InGameOverActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GoToMM.started += instance.OnGoToMM;
                @GoToMM.performed += instance.OnGoToMM;
                @GoToMM.canceled += instance.OnGoToMM;
            }
        }
    }
    public InGameOverActions @InGameOver => new InGameOverActions(this);
    public interface IOnFootActions
    {
        void OnWalking(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnOpenStats(InputAction.CallbackContext context);
        void OnOpenPauseMenu(InputAction.CallbackContext context);
        void OnGetup(InputAction.CallbackContext context);
    }
    public interface IInPauseMenuActions
    {
        void OnReturn(InputAction.CallbackContext context);
        void OnCloseStats(InputAction.CallbackContext context);
    }
    public interface IInGameOverActions
    {
        void OnGoToMM(InputAction.CallbackContext context);
    }
}
